// Generated by LiveScript 1.2.0
(function(){
  var fs, path, relativeRoot, readJSONSync, tryMultiple, mergeDefaults, getConfig;
  fs = require('fs');
  path = require('path');
  relativeRoot = function(it){
    return path.resolve(__dirname, "../", it);
  };
  readJSONSync = function(it){
    var e, code;
    try {
      return JSON.parse(fs.readFileSync(relativeRoot(it)));
    } catch (e$) {
      e = e$, code = e.code;
      switch (code) {
      case "ENOENT":
        return null;
      default:
        throw e;
      }
    }
  };
  tryMultiple = function(files){
    var i$, len$, file, c;
    for (i$ = 0, len$ = files.length; i$ < len$; ++i$) {
      file = files[i$];
      c = readJSONSync(file);
      if (!!c) {
        return c;
      }
    }
    return {};
  };
  mergeDefaults = function(a, fallback){
    var that, k, fb, own$ = {}.hasOwnProperty, results$ = {};
    if (Array.isArray(fallback)) {
      if (that = a) {
        that;
      } else {
        fallback;
      }
    }
    if (typeof fallback === "object") {
      for (k in fallback) if (own$.call(fallback, k)) {
        fb = fallback[k];
        results$[k] = a[k] != null ? mergeDefaults(a[k], fb) : fb;
      }
      return results$;
    } else if (a != null) {
      return a;
    } else {
      return fallback;
    }
  };
  getConfig = function(){
    var HOME;
    HOME = process.env.HOME;
    return mergeDefaults(tryMultiple(['config.json', HOME + "/.config/lights.conf.json"]), readJSONSync('config.default.json'));
  };
  module.exports = getConfig();
}).call(this);
