// Generated by LiveScript 1.2.0
(function(){
  var Lock;
  Lock = (function(){
    Lock.displayName = 'Lock';
    var prototype = Lock.prototype, constructor = Lock;
    prototype.locked = false;
    function Lock(){
      this.requesters = [];
    }
    prototype.get = function(cb){
      if (this.locked) {
        this.requesters.push(cb);
        return false;
      } else {
        this.locked = true;
        cb();
        return true;
      }
    };
    prototype.free = function(){
      if (this.requesters.length) {
        return this.requesters.shift()();
      } else {
        return this.locked = false;
      }
    };
    return Lock;
  }());
  module.exports = Lock;
}).call(this);
